# Generated by Django 5.2.5 on 2026-02-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='total_days',
            field=models.IntegerField(default=4),
        ),
    ]
