# Generated by Django 5.2.5 on 2026-02-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_change_total_days_default_to_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reached_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
