# Generated by Django 5.2.5 on 2026-02-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_add_reached_at_to_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='principal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
