# Generated by Django 5.2.5 on 2026-02-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_add_principal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='expense_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='expense_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='expense_receipt',
            field=models.FileField(blank=True, null=True, upload_to='expense_receipts/'),
        ),
    ]
