# Generated by Django 5.2.11 on 2026-02-28 16:25

from django.db import migrations


def set_existing_users_verified(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.all().update(is_email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_is_email_verified'),
    ]

    operations = [
        migrations.RunPython(
            set_existing_users_verified,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
